import type { Scenario } from "./interview-engine";

const sourceBase = "https://www.hellointerview.com/learn/system-design/problem-breakdowns";

export const scenarios: Scenario[] = [
  { id: "bitly", sourceSlug: "bitly", name: "Design a planet-scale URL shortener", shortName: "Bitly", brief: "Create durable short links and resolve them globally with very low latency.", accent: "Read heavy", scaleAnswer: "Assume 100 million daily users, one billion stored links, a heavily read-skewed workload, sub-100 ms redirects, and 99.99% availability.", functionalAnswer: "Users create a short link, optionally choose an alias or expiry, and resolve it to the original URL. Analytics and advanced abuse detection can be scoped separately." },
  { id: "dropbox", sourceSlug: "dropbox", name: "Design a cloud file storage and sync service", shortName: "Dropbox", brief: "Upload, download, synchronize, and share large files across devices.", accent: "Large blobs", scaleAnswer: "Assume hundreds of millions of users, petabytes of durable blob data, resumable multi-gigabyte uploads, and globally distributed reads.", functionalAnswer: "Users upload, download, synchronize, and share files. Preserve versions and make interrupted transfers resumable without duplicating whole files." },
  { id: "gopuff", sourceSlug: "gopuff", name: "Design a local delivery service", shortName: "Local delivery", brief: "Accept nearby orders, manage inventory, dispatch couriers, and show live progress.", accent: "Real-time state", scaleAnswer: "At peak, support tens of thousands of new orders per minute, hundreds of thousands of active deliveries, and courier locations every few seconds.", functionalAnswer: "Customers browse nearby inventory, order and track; a local facility fulfills; a courier is assigned and reports location. Payroll is out of scope." },
  { id: "ticketmaster", sourceSlug: "ticketmaster", name: "Design a global ticket marketplace", shortName: "Ticketmaster", brief: "Discover events, reserve scarce seats, and purchase safely during extreme onsale spikes.", accent: "High contention", scaleAnswer: "A major onsale can bring over one million users in minutes and tens of thousands of seat-hold attempts per second.", functionalAnswer: "Users discover events, view seats, hold a seat briefly, pay, and receive a ticket. Preventing double-sells is the core invariant." },
  { id: "fb-news-feed", sourceSlug: "fb-news-feed", name: "Design a personalized social news feed", shortName: "FB News Feed", brief: "Publish posts and serve a ranked home feed from friends and creators.", accent: "Fan-out", scaleAnswer: "Assume hundreds of millions of daily users, a read-to-write ratio above 100:1, and celebrity accounts with tens of millions of followers.", functionalAnswer: "Users publish posts, follow people, and load a ranked home feed that respects visibility. Messaging and ads are out of scope." },
  { id: "tinder", sourceSlug: "tinder", name: "Design a swipe-based dating service", shortName: "Tinder", brief: "Recommend nearby profiles, record swipes, form matches, and enable messaging.", accent: "Recommendations", scaleAnswer: "Assume tens of millions of daily users, billions of swipes per day, low-latency candidate generation, and regional location privacy.", functionalAnswer: "Users create profiles, receive candidates, swipe, form a match after mutual interest, and then message. Matching must be race-safe." },
  { id: "leetcode", sourceSlug: "leetcode", name: "Design an online coding judge", shortName: "LeetCode", brief: "Store problems, run untrusted submissions, and return verdicts predictably.", accent: "Sandboxed compute", scaleAnswer: "Support bursty contests with hundreds of thousands of submissions, strict CPU and memory limits, and fair queueing.", functionalAnswer: "Users browse problems, submit code, run it against test cases in isolation, and receive a result. Problem authoring is secondary." },
  { id: "whatsapp", sourceSlug: "whatsapp", name: "Design a global messaging service", shortName: "WhatsApp", brief: "Deliver one-to-one and group messages across intermittently connected devices.", accent: "Realtime delivery", scaleAnswer: "Assume billions of users, hundreds of billions of messages daily, multi-device sessions, and high availability across regions.", functionalAnswer: "Users send and receive messages, see delivery state, participate in groups, and retrieve messages after reconnecting. Define ordering boundaries explicitly." },
  { id: "distributed-rate-limiter", sourceSlug: "distributed-rate-limiter", name: "Design a distributed rate limiter", shortName: "Rate Limiter", brief: "Enforce configurable quotas consistently across a large service fleet.", accent: "Distributed counters", scaleAnswer: "Evaluate millions of decisions per second with single-digit millisecond overhead and tolerate regional or backing-store failure.", functionalAnswer: "Operators define limits by identity and window; callers receive allow or deny plus retry metadata. Discuss accuracy versus availability." },
  { id: "youtube", sourceSlug: "youtube", name: "Design a global video platform", shortName: "YouTube", brief: "Upload, process, discover, and stream video at global scale.", accent: "Media pipeline", scaleAnswer: "Assume billions of viewers, millions of uploads per day, multiple renditions, global delivery, and long-lived petabyte-scale storage.", functionalAnswer: "Creators upload videos; the system transcodes them; viewers discover and stream adaptive renditions. Comments and advertising are optional." },
  { id: "fb-live-comments", sourceSlug: "fb-live-comments", name: "Design live comments for large broadcasts", shortName: "FB Live Comments", brief: "Ingest and fan out a fast-moving comment stream to live viewers.", accent: "Realtime fan-out", scaleAnswer: "A single broadcast may have millions of viewers and hundreds of thousands of comments per minute with bounded delivery lag.", functionalAnswer: "Viewers post comments and receive a relevant live stream with moderation controls. Total ordering is not necessarily required." },
  { id: "top-k", sourceSlug: "top-k", name: "Design a real-time top-K video tracker", shortName: "YouTube Top K", brief: "Continuously rank the most-viewed videos over configurable time windows.", accent: "Stream aggregation", scaleAnswer: "Consume millions of view events per second and refresh top lists within seconds across several windows and regions.", functionalAnswer: "Ingest view events and return the top K videos for a requested window. Define acceptable approximation, lateness, and replay behavior." },
  { id: "uber", sourceSlug: "uber", name: "Design a ride-hailing platform", shortName: "Uber", brief: "Match riders to nearby drivers and track a trip in real time.", accent: "Geo matching", scaleAnswer: "Support millions of concurrent drivers sending frequent locations, city-scale peak bursts, and seconds-level matching latency.", functionalAnswer: "Riders request a trip; nearby drivers receive offers; one accepts; both track the trip through completion. Payments can be a downstream workflow." },
  { id: "web-crawler", sourceSlug: "web-crawler", name: "Design a web crawler", shortName: "Web Crawler", brief: "Discover, fetch, deduplicate, and revisit web pages politely at massive scale.", accent: "Distributed pipeline", scaleAnswer: "Fetch billions of pages, obey per-host politeness and robots policies, deduplicate content, and recover work after failures.", functionalAnswer: "Seed URLs enter a frontier, pages are fetched and parsed, new links are scheduled, and content is stored. Avoid crawl traps and duplicate work." },
  { id: "ad-click-aggregator", sourceSlug: "ad-click-aggregator", name: "Design an ad click aggregator", shortName: "Ad Click Aggregator", brief: "Ingest clicks and produce timely, trustworthy campaign metrics.", accent: "Exactly-once effects", scaleAnswer: "Handle millions of events per second, late and duplicate events, minute-level reporting, and long-term raw-event retention.", functionalAnswer: "Record click events and query aggregates by campaign and time window. Billing-grade counts need a clear deduplication and correction story." },
  { id: "fb-post-search", sourceSlug: "fb-post-search", name: "Design search over social posts", shortName: "FB Post Search", brief: "Index new posts quickly and search only content a viewer may access.", accent: "Search indexing", scaleAnswer: "Index hundreds of millions of daily posts, serve high query volume, and propagate privacy changes within a defined bound.", functionalAnswer: "Users publish posts and search relevant text across content they can view. Ranking, indexing lag, and deletion semantics should be explicit." },
  { id: "yelp", sourceSlug: "yelp", name: "Design a local business discovery service", shortName: "Yelp", brief: "Search nearby businesses, view details, and write reviews.", accent: "Geo search", scaleAnswer: "Serve globally distributed read traffic, millions of businesses and reviews, and low-latency geo-text queries.", functionalAnswer: "Users search by location and category, view a business, and create a review. Business onboarding and ad auctions are out of scope." },
  { id: "instagram", sourceSlug: "instagram", name: "Design a photo sharing network", shortName: "Instagram", brief: "Publish media, follow creators, and retrieve a personalized feed.", accent: "Media + feed", scaleAnswer: "Assume hundreds of millions of daily users, high media bandwidth, read-heavy feeds, and celebrity fan-out.", functionalAnswer: "Users upload photos, follow accounts, and view a home feed. Direct messages and complex editing can be excluded." },
  { id: "strava", sourceSlug: "strava", name: "Design a fitness activity network", shortName: "Strava", brief: "Record GPS activities, compute stats, compare segments, and share updates.", accent: "Geo time series", scaleAnswer: "Ingest large GPS traces, compute derived metrics asynchronously, and handle popular segment leaderboards at global scale.", functionalAnswer: "Athletes upload an activity, view computed metrics, compare segment efforts, and share with followers. Device capture itself is out of scope." },
  { id: "distributed-cache", sourceSlug: "distributed-cache", name: "Design a distributed cache", shortName: "Distributed Cache", brief: "Provide low-latency key-value access across a horizontally scaled cluster.", accent: "Partitioning", scaleAnswer: "Serve millions of operations per second at sub-millisecond to low-millisecond latency while nodes join, fail, and rebalance.", functionalAnswer: "Clients get, set, and delete values with TTLs. Define consistency, eviction, replication, hot-key, and failure behavior." },
  { id: "online-auction", sourceSlug: "online-auction", name: "Design an online auction platform", shortName: "Online Auction", brief: "List items, accept concurrent bids, and close auctions fairly.", accent: "Ordering + contention", scaleAnswer: "Support large global auctions with sudden bid spikes, strict close times, durable bid history, and realtime updates.", functionalAnswer: "Sellers list items; bidders place bids and watch status; the auction closes with one winner. Establish the authoritative ordering rule." },
  { id: "job-scheduler", sourceSlug: "job-scheduler", name: "Design a distributed job scheduler", shortName: "Job Scheduler", brief: "Schedule one-off and recurring work across a fault-tolerant worker fleet.", accent: "Long-running work", scaleAnswer: "Manage millions of scheduled jobs, bursty due times, retries, worker failure, and varied execution durations.", functionalAnswer: "Clients create, cancel, and inspect jobs; workers claim and execute them. Define delivery semantics, retries, leases, and backoff." },
  { id: "google-news", sourceSlug: "google-news", name: "Design a news aggregation service", shortName: "News Aggregator", brief: "Ingest stories, cluster duplicates, rank topics, and personalize a feed.", accent: "Ingestion + ranking", scaleAnswer: "Continuously ingest from many publishers, cluster breaking stories within minutes, and serve global read-heavy feeds.", functionalAnswer: "Collect articles, group versions of the same story, rank stories, and serve a feed. Publisher tools and ads are secondary." },
  { id: "camelcamelcamel", sourceSlug: "camelcamelcamel", name: "Design a price tracking service", shortName: "Price Tracking", brief: "Track product prices over time and notify users when thresholds are crossed.", accent: "Scheduled crawling", scaleAnswer: "Monitor hundreds of millions of product URLs with retailer-specific limits, timely changes, and bursty notification fan-out.", functionalAnswer: "Users track a product and set an alert; the system checks prices, stores history, and notifies on a qualifying change." },
  { id: "robinhood", sourceSlug: "robinhood", name: "Design a retail trading platform", shortName: "Robinhood", brief: "Show market data, accept orders, and maintain trustworthy account state.", accent: "Financial correctness", scaleAnswer: "Handle market-open bursts, high-frequency quote updates, strict auditability, and highly available order intake.", functionalAnswer: "Users view quotes, submit and cancel orders, and inspect positions. Separate order intent, broker or exchange execution, and ledger settlement." },
  { id: "google-docs", sourceSlug: "google-docs", name: "Design collaborative document editing", shortName: "Google Docs", brief: "Let many users edit the same document with fast convergence and durable history.", accent: "Collaboration", scaleAnswer: "Support large documents, many concurrent editors, sub-second propagation, offline reconnects, and durable version history.", functionalAnswer: "Users create, share, edit, and observe collaborators in a document. Define conflict resolution, permissions, and persistence boundaries." },
  { id: "payment-system", sourceSlug: "payment-system", name: "Design a payment processing system", shortName: "Payment System", brief: "Authorize and capture payments without losing or duplicating money movement.", accent: "Ledger integrity", scaleAnswer: "Support global merchants, bursty checkout traffic, external processor failures, multi-day reconciliation, and a full audit trail.", functionalAnswer: "A merchant initiates a payment, receives status, may retry safely, and can refund. The immutable ledger and idempotency rules are central." },
  { id: "metrics-monitoring", sourceSlug: "metrics-monitoring", name: "Design a metrics monitoring platform", shortName: "Metrics Monitoring", brief: "Ingest time-series metrics, query dashboards, and evaluate alerts.", accent: "Time series", scaleAnswer: "Ingest millions of samples per second, retain multiple resolutions, support low-latency range queries, and evaluate alerts continuously.", functionalAnswer: "Agents write metrics; users query dashboards and define alert rules. Address cardinality, downsampling, retention, and delayed data." },
  { id: "online-chess", sourceSlug: "online-chess", name: "Design an online chess service", shortName: "Online Chess", brief: "Match players and run authoritative real-time games with clocks.", accent: "Realtime state", scaleAnswer: "Support millions of concurrent games, low-latency moves, reconnects, fair clocks, and cheating or abuse controls.", functionalAnswer: "Players are matched, exchange legal moves, observe clocks, reconnect, and complete a result. One authority must order moves per game." },
  { id: "chatgpt", sourceSlug: "chatgpt", name: "Design a conversational AI product", shortName: "ChatGPT", brief: "Serve streamed model responses, conversation history, and safety controls at global scale.", accent: "GPU orchestration", scaleAnswer: "Support global bursty demand, long-running streamed inference, scarce accelerator capacity, per-model routing, and graceful overload.", functionalAnswer: "Users start conversations, send prompts, stream responses, and revisit history. Model training is out of scope; focus on serving, safety, and product state." },
];

export const questionSourceUrl = (scenario: Scenario) => `${sourceBase}/${scenario.sourceSlug}`;

export function pickRandomScenario(randomValue = Math.random()): Scenario {
  const bounded = Math.max(0, Math.min(0.999999, randomValue));
  return scenarios[Math.floor(bounded * scenarios.length)];
}
